name = "cors"
main = "src/index.ts"
compatibility_date = "2022-11-24"

kv_namespaces = [
    { binding = "ANALYTICS", id = "24175492bf1e468cb414b494e65aea8d", preview_id = "24175492bf1e468cb414b494e65aea8d" },
]
